spellchecker: aspell

matrix:
- name: mkdocs
  sources:
  - docs/**/*.md
  aspell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
    - .en-custom.txt
    output: build/dictionary/mkdocs.dic
  pipeline:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - 'code, pre'
      - 'a:is(.magiclink-compare, .magiclink-commit, .magiclink-repository)'
      - 'span.keys'
      - '.MathJax_Preview, .md-nav__link, .md-footer-custom-text, .md-source__repository, .headerlink, .md-icon'
      - '.md-social__link'
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '(?<=\w)''s(?!\w)'
        close: '\b'
  - pyspelling.filters.url:
